name: Update README with Activity

on:
  workflow_dispatch:
  pull_request:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
      issues: write      

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: HmtWu
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README with recent activity"
